name: Test Actions
run-name: ${{ github.actor }} is testing out Test Actions
on: [push]
jobs:
  First-Job:
    runs-on: ubuntu-latest
    steps:
      - run: echo  "job triggered by ${{ github.event_name }}"
      - name: Checkout out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
